### ISSUE TITLE
Should write in typescript

### ISSUE THREAD

**Issue by flamefox** [JaspervRijbroek/aurora#36]
ts will be better i think

**Comment by JaspervRijbroek** [comment]
Hi @flamefox, thanks for the ticket, I have checked out typescript but I decided to go with vanilla JS because then you don't have another layer of transcoding which makes it faster also (at least back in the day) the compiled JS that comes out of it is also a little slower.

On the other side I know that typescript takes away a lot of type checking away from the developer whick is very nice.

**Comment by JaspervRijbroek** [comment]
I have been thinking about this for a long time, the compile step can be automated and the code will become a lot more clean. However for those who want to use typescript, they can but the code examples will stay in JS ;).

I have added a feature branch for this.
